services:
  nginx:
    image: nginx:1.25-alpine
    depends_on: [php]
    expose:
      - "80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    command: ["/bin/sh","-c","rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    restart: always

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    environment:
      - TZ=America/Sao_Paulo
      - APP_ENV=prod
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
    restart: always
