name: Deploy to VPS

on:
  push:
    branches:
      - main   # Altere para 'master' se seu branch principal for master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/pineapplelab/petflow.pro
            git pull
            docker-compose restart nginx_petflow
